// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// kern_gaussian
NumericVector kern_gaussian(NumericVector dist, double scal);
RcppExport SEXP recruitR_kern_gaussian(SEXP distSEXP, SEXP scalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type dist(distSEXP);
    Rcpp::traits::input_parameter< double >::type scal(scalSEXP);
    rcpp_result_gen = Rcpp::wrap(kern_gaussian(dist, scal));
    return rcpp_result_gen;
END_RCPP
}
// kern_exponential
NumericVector kern_exponential(NumericVector dist, double scal);
RcppExport SEXP recruitR_kern_exponential(SEXP distSEXP, SEXP scalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type dist(distSEXP);
    Rcpp::traits::input_parameter< double >::type scal(scalSEXP);
    rcpp_result_gen = Rcpp::wrap(kern_exponential(dist, scal));
    return rcpp_result_gen;
END_RCPP
}
// kern_exponential_power
NumericVector kern_exponential_power(NumericVector dist, double scal, double shap);
RcppExport SEXP recruitR_kern_exponential_power(SEXP distSEXP, SEXP scalSEXP, SEXP shapSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type dist(distSEXP);
    Rcpp::traits::input_parameter< double >::type scal(scalSEXP);
    Rcpp::traits::input_parameter< double >::type shap(shapSEXP);
    rcpp_result_gen = Rcpp::wrap(kern_exponential_power(dist, scal, shap));
    return rcpp_result_gen;
END_RCPP
}
// kern_2Dt
NumericVector kern_2Dt(NumericVector dist, double scal, double shap);
RcppExport SEXP recruitR_kern_2Dt(SEXP distSEXP, SEXP scalSEXP, SEXP shapSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type dist(distSEXP);
    Rcpp::traits::input_parameter< double >::type scal(scalSEXP);
    Rcpp::traits::input_parameter< double >::type shap(shapSEXP);
    rcpp_result_gen = Rcpp::wrap(kern_2Dt(dist, scal, shap));
    return rcpp_result_gen;
END_RCPP
}
// kern_lognormal
NumericVector kern_lognormal(NumericVector dist, double scal, double shap);
RcppExport SEXP recruitR_kern_lognormal(SEXP distSEXP, SEXP scalSEXP, SEXP shapSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type dist(distSEXP);
    Rcpp::traits::input_parameter< double >::type scal(scalSEXP);
    Rcpp::traits::input_parameter< double >::type shap(shapSEXP);
    rcpp_result_gen = Rcpp::wrap(kern_lognormal(dist, scal, shap));
    return rcpp_result_gen;
END_RCPP
}
