# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name kernels
#' @title Common seed isotropic dispersal kernels.
#' @description This is a set of five disersal kernel commonly used to model seeds dispersal.
#'
#' @author
#' Kevin Cazelles
#'
#' @param dist a real positive number giving the dispersal distance.
#' @param scal a real positive number giving the scale parameter of the kernel.
#' @param shap a real positive number giving the shape parameter of the kernel.
#'
#' @return The pdf values at distance \code{dist}.
#'
#' @examples
#' seqx <- seq(0,10,0.01)
#' plot(seqx, kern_lognormal(seqx,3,.2), type='l')
#' @references
#' Nathan, R., Klein, E., Robledo-Arnuncio, J.J. and Revilla, E. (2012)
#' Dipsersal Kernels: Review in _Dispersal Ecology and Evolution_. Oxford University Press.
#' @export
kernels <- function() {
    invisible(.Call('_diskers_kernels', PACKAGE = 'diskers'))
}

#' @describeIn kernels Exponential kernel.
#' @export
kern_gaussian <- function(dist, scal) {
    .Call('_diskers_kern_gaussian', PACKAGE = 'diskers', dist, scal)
}

#' @describeIn kernels Exponential kernel.
#' @export
kern_exponential <- function(dist, scal) {
    .Call('_diskers_kern_exponential', PACKAGE = 'diskers', dist, scal)
}

#' @describeIn kernels Dispersal kernels from the exponential-power family.
#' @export
kern_exponential_power <- function(dist, scal, shap) {
    .Call('_diskers_kern_exponential_power', PACKAGE = 'diskers', dist, scal, shap)
}

#' @describeIn kernels 2Dt kernel.
#' @export
kern_2Dt <- function(dist, scal, shap) {
    .Call('_diskers_kern_2Dt', PACKAGE = 'diskers', dist, scal, shap)
}

#' @describeIn kernels Lognormal kernel.
#' @export
kern_lognormal <- function(dist, scal, shap) {
    .Call('_diskers_kern_lognormal', PACKAGE = 'diskers', dist, scal, shap)
}

